#!/bin/sh  # -*- shell-script -*- mode!

# Script for quickly sanity-checking or debugging ../onetime.

PLAINTEXT=test-plaintext-a

echo "Encrypting..."
../onetime --no-trace -e -p test-pad-1 ${PLAINTEXT}
echo "Done."
echo ""

mv ${PLAINTEXT}.onetime quick-check-tmp.onetime

echo "Decrypting..."
../onetime --no-trace -d -p test-pad-1 quick-check-tmp.onetime
echo "Done."
echo ""

if ! cmp quick-check-tmp ${PLAINTEXT}; then
  echo "ERROR: problem"
  ls -l quick-check-tmp.onetime
  diff -u quick-check-tmp ${PLAINTEXT}
  exit 1
fi
