Document: onetime
Title: Debian onetime Manual
Author: <insert document author here>
Abstract: This manual describes what onetime is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/onetime/onetime.sgml.gz

Format: postscript
Files: /usr/share/doc/onetime/onetime.ps.gz

Format: text
Files: /usr/share/doc/onetime/onetime.text.gz

Format: HTML
Index: /usr/share/doc/onetime/html/index.html
Files: /usr/share/doc/onetime/html/*.html


